// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMQk1swHqH7BefduiRwb2jVwfNw2_iPxQ',
    appId: '1:133777418092:web:ac8506c28df8308bd0b549',
    messagingSenderId: '133777418092',
    projectId: 'watchloop-4383c',
    authDomain: 'watchloop-4383c.firebaseapp.com',
    storageBucket: 'watchloop-4383c.appspot.com',
    measurementId: 'G-HH81C0NRSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANpkNf7OmQBI6NJZf5q0LqIf-HEb_yvxg',
    appId: '1:133777418092:android:1bc1bbfbe7096a58d0b549',
    messagingSenderId: '133777418092',
    projectId: 'watchloop-4383c',
    storageBucket: 'watchloop-4383c.appspot.com',
  );
}
